### ISSUE TITLE
Comparison between coq-min-imports and coq-tools/minimize-requires.py

### ISSUE THREAD

**Issue by anton-trunov** [vzaliva/coq-min-imports#9]
There is `minimize-requires.py` file in [coq-tools](https://github.com/JasonGross/coq-tools) script package  by @JasonGross.

What are the differences between these tools? Except the fact that `coq-min-imports` is written in OCaml and available on OPAM, which is great, btw.

**Comment by vzaliva** [comment]
I have not used `minimize-requires.py` although I've used `fndbug.py` from the same package.
I guess the main difference is that my script could be plugged into Makefile as a wrapper around Coq, and thus seamlessly integrate with the existing build process.

My script is just a quick hack I did to solve my need which I decided to release in case somebody find it useful.

**Comment by anton-trunov** [comment]
Thanks for the tool! I'll definitely try it. Especially since it seems to solve the issue of minimizing imports for the whole project. See e.g. [coq-tools #40](https://github.com/JasonGross/coq-tools/issues/40)

**Comment by JasonGross** [comment]
The import minimizer I wrote uses roughly the same strategy, but, if I recall correctly, I had it get import locations from the .glob files, and I definitely put some work in to make it handle multiple requires with comments in the middle, and I believe it uses a binary-search-like algorithm, which is much faster than trying each require inn sequence when there are many unused ones.

**Comment by JasonGross** [comment]
Update on the status of `minimize-requires.py`: It can now read the list of files to update from `_CoqProject` and can sort them by dependency order to avoid re-building later files.
